### ISSUE TITLE
Any plans for a latest release?

### ISSUE THREAD

**Issue by andronat** [Nef10/lcov-reporter-action#313]
Hello! Any plans on bumping to a latest release? Last one is already 1+ years old.

**Comment by Nef10** [comment]
Hey, I created 0.3.2. There shouldn’t be too many changes, mostly dependencies updates plus the usage of the default token which I pulled in from upstream.

However, this will also be the last version with Node v12 support - there are some dependencies which dropped support in their newer versions, which are currently pending updating. I’ll do that when I get around to it and will create another version afterwards.
